package ru.task.tracker.server;

public enum Endpoints {
    GET_ALL_TASKS,
    GET_TASK,
    GET_TASK_ID,
    POST_TASK,
    DELETE_TASK,
    DELETE_TASK_ID,
    GET_EPIC,
    GET_EPIC_ID,
    POST_EPIC,
    DELETE_EPIC,
    DELETE_EPIC_ID,
    GET_SUBTASK,
    GET_SUBTASK_ID,
    POST_SUBTASK,
    DELETE_SUBTASK,
    DELETE_SUBTASK_ID,
    GET_SUBTASK_EPIC_ID,
    GET_TASKS_HISTORY,
    UNKNOWN
}
